<div class="d-flex justify-content-around">
	<div class="">
		<a href="index.php?c=admin&a=grid" class="btn text-white">Admin</a>
	</div>
	<div class="">
		<a href="index.php?c=product&a=grid" class="btn text-white">Product</a>
	</div>
	<div class="">
		<a href="index.php?c=category&a=grid" class="btn text-white">Category</a>
	</div>
	<div class="">
		<a href="index.php?c=customer&a=grid" class="btn text-white">Customer</a>
	</div>
	<div class="">
		<a href="index.php?c=vendor&a=grid" class="btn text-white">Vendor</a>
	</div>
	<div class="">
		<a href="index.php?c=salesman&a=grid" class="btn text-white">Salesman</a>
	</div>
	<div class="">
		<a href="index.php?c=shipping&a=grid" class="btn text-white">Shipping Method</a>
	</div>
	<div class="">
		<a href="index.php?c=payment&a=grid" class="btn text-white">Payment Method</a>
	</div>
	<div class="">
		<a href="index.php?c=eav_attribute&a=grid" class="btn text-white">Eav Attribute</a>
	</div>
</div>