<?php
$products = $this->getProducts();
?>
<div class="container">
	<div class="row mb-3">
		<div class="col-md-6">
			<h2>Manage Products</h2>
		</div>
		<div class="col-md-6 text-end">
			<a href="<?php echo $this->getUrl('add', null , [], true); ?>" class="btn btn-primary">Add Product</a>
		</div>
	</div>
</div>
<div class="row">
	<div class="col table-responsive">
		<?php if (!$products): ?>
			<div class="alert alert-warning" role="alert">
				No data found.
			</div>
		<?php else: ?>
			<table class="table table-striped table-hover text-center">
				<thead>
					<tr class="dd">
						<th>Product ID</th>
						<th>Name</th>
						<th>SKU</th>
						<th>Cost</th>
						<th>Price</th>
						<th>Quantity</th>
						<th>Status</th>
						<th>Created At</th>
						<th>Updated At</th>
						<th>Media</th>
						<th>Edit</th>
						<th>Delete</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($products as $product) : ?>
						<tr>
							<td><?php echo $product->product_id; ?></td>
							<td><?php echo $product->name; ?></td>
							<td><?php echo $product->sku; ?></td>
							<td><?php echo $product->cost; ?></td>
							<td><?php echo $product->price; ?></td>
							<td><?php echo $product->quantity; ?></td>
							<td><?php echo $product->getStatusText(); ?></td>
							<td><?php echo $product->created_at; ?></td>
							<td><?php echo $product->updated_at; ?></td>
							<td><a href="<?php echo $this->getUrl(null, 'product_media', ['id'=> $product->product_id], true);?>" class="btn btn-sm btn-secondary">Media</a></td>
							<td><a href="<?php echo $this->getUrl('edit', null, ['id'=> $product->product_id], true);?>" class="btn btn-sm btn-primary">Edit</a></td>
							<td><a href="<?php echo $this->getUrl('delete', null, ['id'=> $product->product_id], true);?>" class="btn btn-sm btn-danger">Delete</a></td>
						</tr>
					<?php endforeach; ?>
				<?php endif; ?>
			</tbody>
		</table>
	</div>
</div>
