<?php
$shipping = $this->getShipping()['shipping'];
?>
<form action="<?php echo $this->getUrl('save'); ?>" method="post">
	<div class="add">
		<div>Shipping Method</div>
		<div class="cancel">
			<button><a href="<?php echo $this->getUrl('grid', null, [], true); ?>">Cancel</a></button>
		</div>
		<div class="submit">
			<button type="submit">Submit</button>
		</div>
	</div>
	<div>Shipping Method Information</div>
	<table>
		<tr>
			<td>Name</td>
			<td><input type="text" name="shipping[name]" value="<?php echo $shipping->name; ?>"></td>
		</tr>
		<tr>
			<td>Amount</td>
			<td><input type="text" name="shipping[amount]" value="<?php echo $shipping->amount; ?>"></td>
		</tr>
		<tr>
			<td>Status</td>
			<td>
				<select name="shipping[status]">
					<?php foreach ($shipping->getStatusOptions() as $key => $value) : ?>
					<?php $selected = ($key == $shipping->getStatus()) ? "selected" : ''; ?>
					<option value="<?php echo $key; ?>" <?php echo $selected;?>><?php echo $value; ?></option>
					<?php endforeach; ?>
				</select>
			</td>
		</tr>
	</table>
</form>