<?php
$admins = $this->getAdmins();
?>
<div class="container">
	<div class="row mb-3">
		<div class="col-md-6">
			<h2>Manage Admin</h2>
		</div>
			<div class="col-md-6 text-end">
			<a href="<?php echo $this->getUrl('add') ?>">Add Admin</a></div>
</div>
<table width="100%" cellpadding="25%" border="1px">
	<?php if (!$admins): ?>
	<tr>
		<td colspan="8" align="center"><b>No data found.</b></td>
	</tr>
	<?php else: ?>
	<tr>
		<th>Admin Id</th>
		<th>Name</th>
		<th>email</th>
		<th>Status</th>
		<th>Created At</th>
		<th>Updated At</th>
		<th>EDIT</th>
		<th>DELETE</th>
	</tr>
	<?php foreach ($admins as $admin) : ?>
	<tr>
		<td><?php echo $admin->admin_id; ?></td>
		<td><?php echo $admin->name; ?></td>
		<td><?php echo $admin->email; ?></td>
		<td><?php echo $admin->getStatusText(); ?></td>
		<td><?php echo $admin->created_at; ?></td>
		<td><?php echo $admin->updated_at; ?></td>
		<td><a href="<?php echo $this->getUrl('edit', null, ['id' => $admin->admin_id], true) ?>"class="btn btn-sm btn-primary">EDIT</a></td>
		<td><a href="<?php echo $this->getUrl('delete', null, ['id' => $admin->admin_id], true) ?>"class="btn btn-sm btn-primary">DELETE</a></td>
	</tr>
	<?php endforeach; ?>
	<?php endif; ?>
</table>
