<?php
$customers = $this->getCustomers();
?>
<div class="container">
	<div class="row mb-3">
		<div class="col-md-6">
			<h2>Manage Customer</h2>
		</div>
			<div class="col-md-6 text-end">
		<a href="<?php echo $this->getUrl('add', null, [], true);?>">Add Customer</a>
	</div>
</div>
<table width="100%" cellpadding="25%" border="1px">
	<?php if (!$customers): ?>
	<tr>
		<td colspan="8" align="center"><b>No data found.</b></td>
	</tr>
	<?php else: ?>
	<tr>
		<th>Customer Id</th>
		<th>First Name</th>
		<th>Last Name</th>
		<th>email</th>
		<th>Gender</th>
		<th>Mobile</th>
		<th>Status</th>
		<th>Created At</th>
		<th>Updated At</th>
		<th>EDIT</th>
		<th>DELETE</th>
	</tr>
	<?php foreach ($customers as $customer) : ?>
	<tr>
		<td><?php echo $customer->customer_id; ?></td>
		<td><?php echo $customer->first_name; ?></td>
		<td><?php echo $customer->last_name; ?></td>
		<td><?php echo $customer->email; ?></td>
		<td><?php echo $customer->getGenderText(); ?></td>
		<td><?php echo $customer->mobile; ?></td>
		<td><?php echo $customer->getStatusText(); ?></td>
		<td><?php echo $customer->created_at; ?></td>
		<td><?php echo $customer->updated_at; ?></td>
		<td><a href="<?php echo $this->getUrl('edit', null, ['id'=> $customer->customer_id]);?>"class="btn btn-sm btn-primary">EDIT</a></td>
		<td><a href="<?php echo $this->getUrl('delete', null, ['id'=> $customer->customer_id]);?>"class="btn btn-sm btn-danger">DELETE</a></td>
	</tr>
	<?php endforeach; ?>
	<?php endif; ?>
</table>