<?php
$payments = $this->getPayments();
?>
<div class="container">
	<div class="row mb-3">
		<div class="col-md-6">
			<h2>Manage Payment</h2>
		</div>
			<div class="col-md-6 text-end">
		<a href="<?php echo $this->getUrl('add', null, [], true);?>">Add Customer</a>
	</div>
</div>
<table cellpadding="25%" border="1px" width="100%">
	<?php if (!$payments): ?>
	<tr>
		<td colspan="7" align="center"><b>No data found.</b></td>
	</tr>
	<?php else: ?>
	<tr>
		<th>Payment Method Id</th>
		<th>Name</th>
		<th>Status</th>
		<th>Created At</th>
		<th>Updated At</th>
		<th>EDIT</th>
		<th>DELETE</th>
	</tr>
	<?php foreach ($payments as $payment) : ?>
	<tr>
		<td><?php echo $payment->payment_method_id; ?></td>
		<td><?php echo $payment->name; ?></td>
		<td><?php echo $payment->getStatusText(); ?></td>
		<td><?php echo $payment->created_at; ?></td>
		<td><?php echo $payment->updated_at; ?></td>
		<td><a href="<?php echo $this->getUrl('edit', null, ['id'=> $payment->payment_method_id], true);?>"class="btn btn-sm btn-primary">EDIT</a></td>
		<td><a href="<?php echo $this->getUrl('delete', null, ['id'=> $payment->payment_method_id], true);?>"class="btn btn-sm btn-danger">DELETE</a></td>
	</tr>
<?php endforeach; ?>
<?php endif; ?>
</table>
